from api.views import (
    LoginView,
    get_disciplines,
    cronograma,
    get_docentes,
    lancamento_semestre,
    get_perfil,
    get_notificacoes,
    dashboard_coord,
    dashboard_admin,
    dashboard_prof,
    relatorios,
    alocacao_professores,
    alocacao_professores_total_vinculacao,
    alocacao_professores_agenda_professor,
    alocacao_professores_grade_curso,
    alocacao_professores_montar_grade,
    grade_professor,
    disciplinas_professor,
    cursos_disciplinas,
    ocorrencias,
    grade_cursos,
    preferencia_dia,
)
from django.urls import path, include

# Integrar com as telas do Frontend
urlpatterns = [
    path("login", LoginView.as_view(), name="login"),
    path("dashboard-coord", dashboard_coord),
    path("dashboard-admin", dashboard_admin),
    path("dashboard-prof", dashboard_prof),
    path("relatorios", relatorios),
    path("cronograma/", cronograma),
    path("notificacoes/", get_notificacoes),
    path("disciplinas/", get_disciplines),
    path("docentes/", get_docentes),
    path("lancamento-semestre/", lancamento_semestre),
    path("perfil/", get_perfil),
    path("alocacao_professores/", alocacao_professores),
    path("alocacao_professores/total-vinculacao", alocacao_professores_total_vinculacao),
    path("alocacao_professores/agenda-professor", alocacao_professores_agenda_professor),
    path("alocacao_professores/grade_curso", alocacao_professores_grade_curso),
    path("alocacao_professores/montar_grade", alocacao_professores_montar_grade),
    path("grade-professor", grade_professor),
    path("disciplinas-professor", disciplinas_professor),
    path("cursos_disciplinas/", cursos_disciplinas),
    path("ocorrencias/", ocorrencias),
    path("grade-cursos/", grade_cursos),
    path("preferencia-dia/", preferencia_dia),
]
